# Generated by Django 2.0.1 on 2021-10-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('minimum_renting_duration', models.IntegerField(default=1)),
                ('per_night_price', models.FloatField(default=30)),
                ('no_of_rooms', models.IntegerField(default=1, null=True)),
                ('no_of_beds', models.IntegerField(default=1, null=True)),
                ('country', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
